### ISSUE TITLE
No Windows support?

### ISSUE THREAD

**Issue by Godnoken** [kroketio/kotki#1]
I've been following your progress for a few weeks hoping for a simpler way to integrate Marian into an application on Windows.

However, yesterday it seems like you abandoned Windows altogether with [Marian-lite](https://github.com/kroketio/marian-lite).
Do you plan on keeping it Linux only, or is possible to compile a windows .lib version if I were to install Debian?

Cheers!

**Comment by kroketio** [comment]
Hello, please note Kotki is still very much an on-going effort. I expect another 'usable release' in a week. Current master is in a half-development state.

### Roadmap

1. [x] fork bergamot
    - [x] rename to 'kotki'
    - [x] simplify CMake build system
    - [x] provide a simpler API in both C++ and Python
    - [x] provide easy-to-download language packs (on the release page)
2. [ ] fork marian
    - [x] rename to 'marian-lite'
    - [x] simplify CMake build system
    - [x] prefer system libraries over vendored libraries
        - (which will require you to install the following libs manually):
            - https://github.com/kroketio/intgemm/
            - https://github.com/kroketio/pathie-cpp/
            - https://github.com/kroketio/sentencepiece-browsermt/
            - (and also; provide debian packaging for all of the above)
    - [ ] test it
3. [ ] fix kotki
    - [x] make kotki link against the new 'marian-lite' (latest master has this)
    - [ ] fix Python bindings, as it now depends on the new 'marian-lite', which it needs to install during `pip install`
    - [ ] Make kotki work on devices that run https://maemo-leste.github.io/ (ARM)
4. [ ] Possibly port to other platforms*
    - Android
    - Windows
    - Applet

### *Windows (and other platforms)

Part of my *'simplify CMake build system'* efforts is to initially focus on supporting just one platform - in favor of writing CMake config files that are easy to understand.  For example, the old Marian (and Bergamot) CMake supports a range of platforms (Apple, Windows, Linux, WASM), a range of compilers (MSVC, Clang, GNU) and a range of CMake versions. This results in some verbose CMake that is challenging to compile, package, distribute.

Inevitably we, or others (like yourself) will want to use Kotki on Windows, or other platforms. We will accept such PRs but only if they respect to "keep things simple" as Kroket Ltd. currently does not have a business case to support Windows, so it is kinda hard to justify spending time on it. We would essentially create the expectation that Windows (or other platforms) are supported targets where things are constantly in a working and maintained state.

Most likely we will be doing some cross-compiling tests with mingw soon (again, when we have time, or when business requires it). Perhaps it compiles into a usable Windows library with minimal effort, that would surely be nice - but for now not a priority.

**Comment by kroketio** [comment]
For any reading who want Windows support (or any other platform) - do not wait for us, fork and provide support! The power of open-source :+1: Kotki, at least for now, will stay Linux only.

**Comment by Godnoken** [comment]
Thank you for the elaborate response.

You'll have to excuse my slow response, I've been busy with work & holidays.

I fully understand & respect the decision to focus only on Linux. For now I've decided to go down the route of using TranslateLocally & NativeMessaging but I may have reason to come back to this as I gain more experience.
